// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'customer_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CustomerModel _$CustomerModelFromJson(Map<String, dynamic> json) =>
    CustomerModel(
      id: json['id'] as String?,
      groupId: json['group_id'] as String?,
      noCust: json['custno'] as String?,
      typeInstallasi: json['jenis_pasang'] as String?,
      username: json['username'] as String?,
      password: json['password'] as String?,
      titleJob: json['jabatan'] as String?,
      firstname: json['fname'] as String?,
      lastName: json['lname'] as String?,
      emailCustomer: json['email_cust'] as String?,
      gender: json['kelamin'] as String?,
      noTelp: json['no_telepon'] as String?,
      noMobilePhone: json['no_hp'] as String?,
      identityCard: json['pengenal'] as String?,
      noIdentity: json['no_pengenal'] as String?,
      addressCust: json['alamat'] as String?,
      zipCode: json['kodepos'] as String?,
      photo: json['photo'] as String?,
      signature: json['signature'] as String?,
      regencyId: json['kab_id'] as String?,
      districId: json['kec_id'] as String?,
      villageId: json['desa_id'] as String?,
      longitude: json['longitude'] as String?,
      latitude: json['latitude'] as String?,
      typeService: json['jenis'] as String?,
      serviceId: json['layanan_id'] as String?,
      packetId: json['paket_id'] as String?,
      typePacket: json['kapasitas'] as String?,
      coverageCheck: json['cek_alamat_psg'] as String?,
      addressInst: json['alamat_psg'] as String?,
      zipCodeInst: json['kodepos_psg'] as String?,
      regencyIdInst: json['kab_id_psg'] as String?,
      districkIdInst: json['kec_id_psg'] as String?,
      villageIdInst: json['desa_id_psg'] as String?,
      placeStatus: json['status_tempat'] as String?,
      corporation: json['perusahaan'] as String?,
      addressCorp: json['alamat_usaha'] as String?,
      telpCorp: json['telp_usaha'] as String?,
      taxId: json['npwp'] as String?,
      office: json['kantor'] as String?,
      typeBussiness: json['jenis_usaha'] as String?,
      website: json['website'] as String?,
      nameBussiness: json['finansial_nama'] as String?,
      titleBussiness: json['finansial_jabatan'] as String?,
      addressBussiness: json['finansial_alamat'] as String?,
      zipCodeBussines: json['finansial_kodepos'] as String?,
      mobileBussiness: json['finansial_ponsel'] as String?,
      telpBussines: json['finansial_telepon'] as String?,
      faxBussiness: json['finansial_fax'] as String?,
      emailBussiness: json['finansial_email'] as String?,
      nameTechnician: json['teknis_nama'] as String?,
      titleTecnichian: json['teknis_jabatan'] as String?,
      mobileTechnician: json['teknis_ponsel'] as String?,
      telpTechnician: json['teknis_telepon'] as String?,
      emailTechnician: json['teknis_email'] as String?,
      activationCode: json['activation_code'] as String?,
      forgotPasswdCode: json['forgotten_password_code'] as String?,
      forgotPasswdTime: json['forgotten_password_time'] as String?,
      rememberCode: json['remember_code'] as String?,
      lastLogin: json['last_login'] as String?,
      active: json['active'] as String?,
      status: json['status'] as String?,
      subscribe: json['berlangganan'] as String?,
      asal: json['asal'] as String?,
      dateRegister: json['tgl_daftar'] as String?,
      dateInst: json['tgl_pasang'] as String?,
      dateActive: json['tgl_aktif'] as String?,
      type: json['tipe'] as String?,
      idSales: json['sales_id'] as String?,
      nameSales: json['sales_name'] as String?,
      monthlyPrice: json['biaya_bulanan'] as String?,
      taxPrice: json['biaya_tax'] as String?,
      regPrice: json['biaya_registrasi'] as String?,
      materialPrice: json['biaya_material'] as String?,
      otherPrice: json['biaya_lain'] as String?,
      priceAll: json['biaya_total'] as String?,
    );

Map<String, dynamic> _$CustomerModelToJson(CustomerModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'group_id': instance.groupId,
      'custno': instance.noCust,
      'jenis_pasang': instance.typeInstallasi,
      'username': instance.username,
      'password': instance.password,
      'jabatan': instance.titleJob,
      'fname': instance.firstname,
      'lname': instance.lastName,
      'email_cust': instance.emailCustomer,
      'kelamin': instance.gender,
      'no_telepon': instance.noTelp,
      'no_hp': instance.noMobilePhone,
      'pengenal': instance.identityCard,
      'no_pengenal': instance.noIdentity,
      'alamat': instance.addressCust,
      'kodepos': instance.zipCode,
      'photo': instance.photo,
      'signature': instance.signature,
      'kab_id': instance.regencyId,
      'kec_id': instance.districId,
      'desa_id': instance.villageId,
      'longitude': instance.longitude,
      'latitude': instance.latitude,
      'jenis': instance.typeService,
      'layanan_id': instance.serviceId,
      'paket_id': instance.packetId,
      'kapasitas': instance.typePacket,
      'cek_alamat_psg': instance.coverageCheck,
      'alamat_psg': instance.addressInst,
      'kodepos_psg': instance.zipCodeInst,
      'kab_id_psg': instance.regencyIdInst,
      'kec_id_psg': instance.districkIdInst,
      'desa_id_psg': instance.villageIdInst,
      'status_tempat': instance.placeStatus,
      'perusahaan': instance.corporation,
      'alamat_usaha': instance.addressCorp,
      'telp_usaha': instance.telpCorp,
      'npwp': instance.taxId,
      'kantor': instance.office,
      'jenis_usaha': instance.typeBussiness,
      'website': instance.website,
      'finansial_nama': instance.nameBussiness,
      'finansial_jabatan': instance.titleBussiness,
      'finansial_alamat': instance.addressBussiness,
      'finansial_kodepos': instance.zipCodeBussines,
      'finansial_ponsel': instance.mobileBussiness,
      'finansial_telepon': instance.telpBussines,
      'finansial_fax': instance.faxBussiness,
      'finansial_email': instance.emailBussiness,
      'teknis_nama': instance.nameTechnician,
      'teknis_jabatan': instance.titleTecnichian,
      'teknis_ponsel': instance.mobileTechnician,
      'teknis_telepon': instance.telpTechnician,
      'teknis_email': instance.emailTechnician,
      'activation_code': instance.activationCode,
      'forgotten_password_code': instance.forgotPasswdCode,
      'forgotten_password_time': instance.forgotPasswdTime,
      'remember_code': instance.rememberCode,
      'last_login': instance.lastLogin,
      'active': instance.active,
      'status': instance.status,
      'berlangganan': instance.subscribe,
      'asal': instance.asal,
      'tgl_daftar': instance.dateRegister,
      'tgl_pasang': instance.dateInst,
      'tgl_aktif': instance.dateActive,
      'tipe': instance.type,
      'sales_id': instance.idSales,
      'sales_name': instance.nameSales,
      'biaya_bulanan': instance.monthlyPrice,
      'biaya_tax': instance.taxPrice,
      'biaya_registrasi': instance.regPrice,
      'biaya_material': instance.materialPrice,
      'biaya_lain': instance.otherPrice,
      'biaya_total': instance.priceAll,
    };
